"""
Generate app.yaml files from environment configuration.
Run during infra setup to template app.yaml with actual values.
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from config.settings import (
    databricks_cfg, delta_cfg, zerobus_cfg,
    lakebase_cfg, app_cfg,
)

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ── Shared env vars for both apps ─────────────────────────────────────────────
SHARED_ENV_VARS = {
    "CATALOG": delta_cfg.catalog,
    "SCHEMA": delta_cfg.schema,
    "TABLE_NAME": delta_cfg.table_name,
    "ZEROBUS_SERVER_ENDPOINT": zerobus_cfg.server_endpoint,
    "ZEROBUS_CLIENT_ID": zerobus_cfg.client_id,
    "ZEROBUS_TOPIC": zerobus_cfg.topic,
    "DATABRICKS_HOST": databricks_cfg.host,
    "DATABRICKS_WAREHOUSE_ID": databricks_cfg.warehouse_id,
    "LAKEBASE_HOST": lakebase_cfg.host,
    "LAKEBASE_PORT": str(lakebase_cfg.port),
    "LAKEBASE_DATABASES": lakebase_cfg.database,
    "LAKEBASE_SCHEMA": lakebase_cfg.schema,
    "LAKEBASE_CATALOG": lakebase_cfg.catalog,
    "STREAM_INTERVAL_MS": str(zerobus_cfg.stream_interval_ms),
    "ACTIVE_WINDOW_SECONDS": str(lakebase_cfg.active_window_seconds),
}

# ── App-specific vars ─────────────────────────────────────────────────────────
MOBILE_ONLY = {
    "MOBILE_APP": app_cfg.mobile_app_name,
}

DASHBOARD_ONLY = {
    "DASHBOARD_APP": app_cfg.dashboard_app_name,
}


def generate_yaml(app_name: str, env_vars: dict) -> str:
    """Generate app.yaml content."""
    lines = [
        "# =============================================================================",
        f"# Databricks Apps configuration for ZeroStream {app_name}",
        "# AUTO-GENERATED by infra/generate_app_yaml.py - DO NOT EDIT MANUALLY",
        "# =============================================================================",
        "command:",
        '  - "uvicorn"',
        '  - "app:app"',
        '  - "--host"',
        '  - "0.0.0.0"',
        '  - "--port"',
        '  - "8000"',
        '  - "--workers"',
        '  - "1"',
        '  - "--log-level"',
        '  - "info"',
        "",
        "env:",
    ]
    
    for key, value in env_vars.items():
        if value is not None and value != "":
            lines.append(f'  - name: "{key}"')
            lines.append(f'    value: "{value}"')
    
    lines.extend([
        "",
        "# ============================================================================",
        "# SECRETS: Configure these in Databricks Apps UI",
        "# ============================================================================",
        "# Apps > [app-name] > Settings > Environment Variables",
        "# - ZEROBUS_CLIENT_SECRET (if using ZeroBus OAuth)",
        "#",
        "# For Lakebase access, add as app resource instead:",
        "# Apps > [app-name] > Settings > Resources > Add Lakebase database",
        "# This auto-injects: PGHOST, PGDATABASE, PGUSER, PGPASSWORD, PGPORT",
        "# ============================================================================",
    ])
    
    return "\n".join(lines) + "\n"


def main():
    print("\n═══════════════════════════════════════════════════")
    print("  Generating app.yaml files from configuration")
    print("═══════════════════════════════════════════════════\n")
    
    # Mobile app
    mobile_vars = {**SHARED_ENV_VARS, **MOBILE_ONLY}
    mobile_yaml = generate_yaml("Mobile Simulator", mobile_vars)
    mobile_path = os.path.join(ROOT_DIR, "mobile_app", "app.yaml")
    
    with open(mobile_path, "w") as f:
        f.write(mobile_yaml)
    print(f"✅ Generated: {mobile_path}")
    
    # Dashboard app
    dashboard_vars = {**SHARED_ENV_VARS, **DASHBOARD_ONLY}
    dashboard_yaml = generate_yaml("Dashboard", dashboard_vars)
    dashboard_path = os.path.join(ROOT_DIR, "dashboard_app", "app.yaml")
    
    with open(dashboard_path, "w") as f:
        f.write(dashboard_yaml)
    print(f"✅ Generated: {dashboard_path}")
    
    print("\n═══════════════════════════════════════════════════")
    print("  ✅ app.yaml files generated!")
    print("═══════════════════════════════════════════════════\n")


if __name__ == "__main__":
    main()
