#!/usr/bin/env bash
# =============================================================================
# ZeroStream - Infrastructure Setup
# Creates all required Databricks resources before deployment
# 
# Usage: bash infra/setup_infra.sh
#
# This script will:
#   1. Create a SQL Warehouse
#   2. Create Databricks Apps (mobile, dashboard)
#   3. Create Lakebase PostgreSQL instance
#   4. Create ZeroBus service principal with OAuth credentials
#   5. Grant warehouse and Lakebase permissions to app service principals
#
# Reads configuration from .env file:
#   INFRA_PREFIX, WAREHOUSE_NAME, WAREHOUSE_CLUSTER_SIZE,
#   MOBILE_APP_NAME, DASHBOARD_APP_NAME,
#   LAKEBASE_INSTANCE, LAKEBASE_CAPACITY,
#   APP_COMPUTE_SIZE, ZEROBUS_TOPIC, ZEROBUS_SP_NAME
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

# Load environment
if [ -f "$ROOT_DIR/.env" ]; then
    set -a
    source "$ROOT_DIR/.env"
    set +a
    echo "✅ Loaded .env from $ROOT_DIR"
else
    echo "❌ .env not found at $ROOT_DIR/.env"
    echo "   Create .env with required variables"
    exit 1
fi

# ── Colours ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

log()     { echo -e "\n${CYAN}[$(date +%H:%M:%S)]${RESET} ${BOLD}$*${RESET}"; }
ok()      { echo -e "  ${GREEN}✅${RESET} $*"; }
warn()    { echo -e "  ${YELLOW}⚠️ ${RESET} $*"; }
err()     { echo -e "  ${RED}❌${RESET} $*"; exit 1; }
divider() { echo -e "  ${CYAN}─────────────────────────────────────────────────${RESET}"; }

STEP=0
TOTAL=10

step() {
    STEP=$((STEP + 1))
    echo ""
    divider
    echo -e "  ${BOLD}Step ${STEP}/${TOTAL}: $*${RESET}"
    divider
}

# ── Header ─────────────────────────────────────────────────────────────────────
clear
echo ""
echo -e "${BOLD}${CYAN}╔═══════════════════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}${CYAN}║       ZeroStream - Infrastructure Setup               ║${RESET}"
echo -e "${BOLD}${CYAN}║   Creates Warehouse, Apps, and ZeroBus Credentials    ║${RESET}"
echo -e "${BOLD}${CYAN}╚═══════════════════════════════════════════════════════╝${RESET}"
echo ""
echo -e "  ${BOLD}Configuration from .env:${RESET}"
echo -e "  Prefix           : ${CYAN}${INFRA_PREFIX:-not set}${RESET}"
echo -e "  Warehouse        : ${CYAN}${WAREHOUSE_NAME:-not set}${RESET} (${WAREHOUSE_CLUSTER_SIZE:-Small})"
echo -e "  Mobile App       : ${CYAN}${MOBILE_APP_NAME:-not set}${RESET}"
echo -e "  Dashboard App    : ${CYAN}${DASHBOARD_APP_NAME:-not set}${RESET}"
echo -e "  Lakebase         : ${CYAN}${LAKEBASE_INSTANCE:-not set}${RESET} (${LAKEBASE_CAPACITY:-CU_1})"
echo -e "  App Compute      : ${CYAN}${APP_COMPUTE_SIZE:-MEDIUM}${RESET}"
echo -e "  ZeroBus SP       : ${CYAN}${ZEROBUS_SP_NAME:-not set}${RESET}"
echo -e "  ZeroBus Topic    : ${CYAN}${ZEROBUS_TOPIC:-not set}${RESET}"
echo ""

# ── Step 1: Validate prerequisites ─────────────────────────────────────────────
step "Validate Prerequisites"

# Check required env vars
required_vars=(
    "DATABRICKS_HOST"
    "DATABRICKS_TOKEN"
    "INFRA_PREFIX"
    "WAREHOUSE_NAME"
    "MOBILE_APP_NAME"
    "DASHBOARD_APP_NAME"
    "ZEROBUS_SP_NAME"
)

for var in "${required_vars[@]}"; do
    if [ -z "${!var:-}" ]; then
        err "$var not set in .env"
    fi
done

# Check Databricks CLI
if ! command -v databricks &>/dev/null; then
    err "Databricks CLI not installed. Run: pip install databricks-cli"
fi

# Check Python
if ! command -v python3 &>/dev/null; then
    err "Python 3 not found"
fi

# Check databricks-sdk
if ! python3 -c "import databricks.sdk" 2>/dev/null; then
    warn "databricks-sdk not installed, installing..."
    pip install databricks-sdk
fi

ok "All prerequisites validated"

# ── Step 1: Initialize generated_config.env with Base Configuration ────────────
step "Initialize generated_config.env with Base Configuration"

CONFIG_FILE="${ROOT_DIR}/generated_config.env"
{
    echo "# Generated by infra/setup_infra.sh"
    echo "# This is the single source of truth for all configuration"
    echo "# Generated on: $(date)"
    echo ""
    echo "# ── Base Configuration (from .env) ─────────────────────────────────"
    echo "DATABRICKS_HOST=${DATABRICKS_HOST}"
    echo "DATABRICKS_TOKEN=${DATABRICKS_TOKEN}"
    echo ""
    echo "# ── Unity Catalog ──────────────────────────────────────────────────"
    echo "CATALOG=${CATALOG:-}"
    echo "SCHEMA=${SCHEMA:-}"
    echo "TABLE_NAME=${TABLE_NAME:-sensor_stream}"
    echo ""
    echo "# ── ZeroBus Base ───────────────────────────────────────────────────"
    echo "ZEROBUS_SERVER_ENDPOINT=${ZEROBUS_SERVER_ENDPOINT:-}"
    echo "ZEROBUS_TOPIC=${ZEROBUS_TOPIC:-}"
    echo ""
    echo "# ── Lakebase Connection ───────────────────────────────────────────"
    echo "LAKEBASE_INSTANCE=${LAKEBASE_INSTANCE:-}"
    echo "LAKEBASE_CATALOG=${LAKEBASE_CATALOG:-}"
    echo "LAKEBASE_DATABASES=${LAKEBASE_DATABASES:-}"
    echo "LAKEBASE_SCHEMA=${LAKEBASE_SCHEMA:-}"
    echo "LAKEBASE_PORT=${LAKEBASE_PORT:-}"
    echo "LAKEBASE_CAPACITY=${LAKEBASE_CAPACITY:-}"
    echo ""
    echo "# ── App Settings ───────────────────────────────────────────────────"
    echo "STREAM_INTERVAL_MS=${STREAM_INTERVAL_MS:-5000}"
    echo "ACTIVE_WINDOW_SECONDS=${ACTIVE_WINDOW_SECONDS:-5}"
    echo ""
    echo "# ── Generated Resources (populated by subsequent steps) ────────────"
} > "$CONFIG_FILE"

ok "Base configuration saved to generated_config.env"

# ── Step 2: Create SQL Warehouse ───────────────────────────────────────────────
step "Create SQL Warehouse"

python3 "${SCRIPT_DIR}/create_warehouse.py" || err "Failed to create SQL warehouse"

ok "SQL Warehouse ready"

# ── Step 3: Create Databricks Apps ─────────────────────────────────────────────
step "Create Databricks Apps"

python3 "${SCRIPT_DIR}/create_apps.py" || err "Failed to create apps"

ok "Databricks Apps created"

# ── Step 4: Create Delta Tables ────────────────────────────────────────────────
step "Create Catalog, Schema, and Delta Tables"

python3 "${SCRIPT_DIR}/create_delta_tables.py" || err "Failed to create Delta tables"

ok "Delta tables created"

# ── Step 5: Create Lakebase Instance ─────────────────────────────────────────
step "Create Lakebase PostgreSQL Instance"

if [ -n "${LAKEBASE_INSTANCE:-}" ]; then
    python3 "${SCRIPT_DIR}/create_lakebase.py" || warn "Failed to create Lakebase instance"
    ok "Lakebase instance ready"
else
    warn "LAKEBASE_INSTANCE not set - skipping Lakebase creation"
fi

# ── Step 6: Create Synced Table ────────────────────────────────────────────────
#step "Create Lakebase Synced Table (Delta → PostgreSQL)"

#if [ -n "${LAKEBASE_INSTANCE:-}" ]; then
#    python3 "${SCRIPT_DIR}/create_synced_table.py" || warn "Synced table setup had issues"
#    ok "Synced table configured"
#else
#    warn "LAKEBASE_INSTANCE not set - skipping synced table creation"
#fi

# ── Step 6: Create ZeroBus Service Principal ───────────────────────────────────
step "Create ZeroBus Service Principal & Credentials"

python3 "${SCRIPT_DIR}/create_zerobus_credentials.py" || err "Failed to create ZeroBus credentials"

ok "ZeroBus credentials created"

# ── Step 7: Grant Permissions ─────────────────────────────────────────────
step "Grant Warehouse & Lakebase Permissions to App Service Principals"

python3 "${SCRIPT_DIR}/grant_permissions.py" || warn "Some permissions may need manual setup"

ok "Permissions configured"

# ── Step 8: Generate app.yaml files ────────────────────────────────────────────
step "Generate app.yaml Configuration Files"

python3 "${SCRIPT_DIR}/generate_app_yaml.py" || err "Failed to generate app.yaml files"

ok "app.yaml files generated from configuration"

# ── Summary ────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}╔═══════════════════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}${GREEN}║       ✅ Infrastructure Setup Complete!               ║${RESET}"
echo -e "${BOLD}${GREEN}╚═══════════════════════════════════════════════════════╝${RESET}"
echo ""
echo -e "  ${BOLD}Configuration saved to:${RESET}"
echo -e "  ${CYAN}${CONFIG_FILE}${RESET}"
echo ""
echo -e "  ${BOLD}Note:${RESET} generated_config.env is the single source of truth."
echo -e "  All apps and scripts load configuration from this file."
echo ""
echo -e "  ${BOLD}Next Steps:${RESET}"
echo -e "  1. Review ${CYAN}generated_config.env${RESET}"
echo -e "  2. Run ${CYAN}bash deployment/deploy_all.sh${RESET} to deploy the apps"
echo ""
